Feature/giseong signup
wecode-bootcamp-korea/32-westagram-backend-2-team pull request #15
Opened 2022-04-18 05:34 UTC by jiggyjiggy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- ValidationError를 사용한 error module화 (사용자 정의 error가 아닌)
		 
## 수정 사항들 자세한 내용
- django.core.exception 의 ValidationError를 사용하여 error를 module화 함

## 기타 질문 및 특이 사항
- KeyError도 묶을 방법..?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 07:07 UTC, kyeongraekim requested changes

2022-04-18 07:07 UTC, kyeongraekim commented on students/giseong/users/validators.py
> +
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

from django.core.exceptions import ValidationError

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

def validate_email(value) :    
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_EMAIL_ADDRESS')

def validate_password(value) :
    if not re.match(REGEX_EMAIL, value):
        raise ValidationError('INVALID_PASSWORD')

2022-04-18 07:48 UTC, jiggyjiggy commented on students/giseong/users/validators.py
> +
경래님이 말씀해주신 내용을 공식문서에서 찾아봤는데 직접적으로 명시된 내용을 찾지 못했습니다
혹시 https://docs.python.org/3/howto/regex.html#match-versus-search에서 표현한 code 때문에 그렇게 해석되는걸까요?

2022-04-18 08:06 UTC, kyeongraekim commented on students/giseong/users/validators.py
> +
https://docs.python.org/3/library/re.html#re.compile 

위 링크 compile 부분에 더 많은 재사용성이 확보될 때 효율이 높아진다는 점이 명시되어 있습니다~

2022-04-18 08:07 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-18 08:07 UTC, merged

2022-04-18 08:09 UTC, jiggyjiggy commented on students/giseong/users/validators.py
> +
좋은 자료 감사합니다!!

2022-04-19 05:38 UTC, BDjaekwanee commented on students/giseong/users/views.py
> +            exist_email(phone_number)
mission 4 branch 에서 확인해 보았는데 이전 수정사항을 반영하려면 해당 브랜치로 넘어와야되어서 여기에 피어리뷰 남깁니다!  
여기 인자값을 exist_email(email)로 들어가야 될거 같아요! 혹시 몰라서 validators.py 에서 다른 의도인지 확인해 보았는데, Parameter는 email로 되어 있더라고요!

2022-04-19 05:39 UTC, jiggyjiggy commented on students/giseong/users/views.py
> +            exist_email(phone_number)
네 잘못 썻네요 
해당 부분 수정하겠습니다
감사합니다