login view
wecode-bootcamp-korea/32-westagram-backend-2-team pull request #16
Opened 2022-04-18 09:49 UTC by jeajeongwook

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 view 작성 및 url 연결 작업 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 view 작성
- urls에 /login 작성 후 LogInView 연결 
- 로그인 시 유도한 에러 및 성공여부 확인

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- password = data['password'], email = data["email"] 해당 부분을 더 간소화 할수도 있을거 같은데 방법이 떠오르지 않습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 11:32 UTC, jiggyjiggy commented on students/jeongwook/users/views.py
> +                return JsonResponse({"message":"INVALID_USER"}, status=401)
module 화 해보시면 좋을 것 같습니다

2022-04-18 11:33 UTC, jiggyjiggy commented on students/jeongwook/users/views.py
> +        data      = json.loads(request.body)
필요없는 여백 없애는게 좋을 것 같습니다

2022-04-18 11:56 UTC, jeajeongwook commented on students/jeongwook/users/views.py
> +                return JsonResponse({"message":"INVALID_USER"}, status=401)
module 화 처리했습니다

2022-04-18 11:56 UTC, jeajeongwook commented on students/jeongwook/users/views.py
> +        data      = json.loads(request.body)
수정했습니다~

2022-04-18 12:04 UTC, jiggyjiggy commented on students/jeongwook/users/views.py
> +            return JsonResponse({"message": err.messages}, status=400)
status=401 으로 수정해야 할 것 같습니다

2022-04-19 00:49 UTC, jeajeongwook commented on students/jeongwook/users/views.py
> +            return JsonResponse({"message": err.messages}, status=400)
401로 수정완료 했습니다!

2022-04-19 01:16 UTC, jiggyjiggy commented on students/jeongwook/users/views.py
> +        data      = json.loads(request.body)
40번 줄의 여백을 언급한거였습니다~!
다시 확인해주시면 감사하겠습니다

2022-04-19 01:25 UTC, jeajeongwook commented on students/jeongwook/users/views.py
> +        data      = json.loads(request.body)
아 다른 부분을 수정했었네요 해당부분 수정하고 몇몇 부분도 가독성 좋게 수정했습니다!

2022-04-19 01:38 UTC, jiggyjiggy commented on students/jeongwook/users/validation.py
> +        raise ValidationError ("INVALID_USER")
비밀번호 조건을 다시 생각해야 할 것 같습니다
존재하는 email , 존재하는 password 면 해당 error message를 반환하지 않을 것으로 보입니다

2022-04-19 01:39 UTC, jiggyjiggy commented on students/jeongwook/users/validation.py
> +        raise ValidationError ("INVALID_USER")
26번 줄 
비밀번호 조건을 다시 생각해야 할 것 같습니다
존재하는 email , 존재하는 password 면 해당 error message를 반환하지 않을 것으로 보입니다

2022-04-19 05:17 UTC, jiggyjiggy commented
LGTM~~!
제가 보기에는 깔끔하게 잘 쓰신 것 같습니다

2022-04-19 05:26 UTC, kyeongraekim requested changes

2022-04-19 05:26 UTC, kyeongraekim commented on students/jeongwook/users/views.py
> +            user_match(email, password)
- 해당 내용은 모듈화를 굳이 안해주셔도 될만큼 가벼운 비즈니스 로직이라고 생각이 되네요. 해당 View의 전반적인 기능을 한눈에 확인하기 쉽게 이곳에 풀어서 진행해보는 것은 어떨까요?
- 위항목 한번 고민하여서 그대로 가실건지 아니면 풀어내볼건지 한 번 고민해보세요!~

2022-04-19 05:47 UTC, jeajeongwook commented
말씀해주신 부분 한번더 view에 넣는 작업을 해보는게 더 익숙해지는데 도움이 될거 같아서 수정했습니다!

2022-04-19 07:24 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-19 07:24 UTC, merged