[박현지] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/32-westagram-backend-2-team pull request #18
Opened 2022-04-18 15:29 UTC by celeste-6

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

- Created LogInView for user Login
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

- checked if credentials passed (email, password, mobile_number) matched database
- added try/except clause to check for errors
- returned 400 if email or password was not submitted
- returned 401 if email or password was not valid
- returned 200 if credentials were valid

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-18 15:46 UTC, BDjaekwanee reviewed
LGTM!  한번 SignUpView 정규식 부분과 LogInView 검증 부분을 validation.py 파일로 모듈화 해보면 좋을거 같아요!

2022-04-19 01:09 UTC, jiggyjiggy commented on students/hyunji/users/views.py
> +from ast import AsyncFunctionDef
필요 없는 import 는 삭제해주시는게 좋을 것 같습니다

2022-04-19 04:30 UTC, celeste-6 commented on students/hyunji/users/views.py
> +from ast import AsyncFunctionDef
오타치다가 들어간걸로 보이네요.. 수정하였습니다!

2022-04-19 04:59 UTC, jiggyjiggy commented
LGTM~~!
제가 보기에는 깔끔하게 잘 작성하신 것 같습니다

2022-04-19 05:12 UTC, kyeongraekim requested changes

2022-04-19 05:12 UTC, kyeongraekim commented on students/hyunji/users/views.py
> +class LogInView(View):
클래스 시작에 앞서서 가독성을 위해 공백 한줄 추가해주세요~

2022-04-19 05:12 UTC, kyeongraekim commented on students/hyunji/users/views.py
> +            else:
논리 연계상 else로의 추가 분기 없이 진행하면 어떨까요?

2022-04-20 01:26 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-20 01:27 UTC, merged