[지기성] Mission 2 모델링
wecode-bootcamp-korea/32-westagram-backend-2-team pull request #7
Opened 2022-04-14 08:48 UTC by jiggyjiggy

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 'users' app 생성 & models.py 작성
		 
## 수정 사항들 자세한 내용
- user 정보의 유효성은 회원가입에서 처리했을 거라 생각해서 저장만 하도록 했습니다
- email , phone number로는 중복을 허용하지 않게 하기위해 unique 속성을 썻습니다

## 기타 질문 및 특이 사항
- commit은 app 생성 때 1회, model 작성 후 1회 하는게 맞나요? (별 생각없이 model 작성 후 1회만 했음)
- User class 에서 유효성 검사는 필요없을 거라 생각되는데 맞나요? (회원가입에서 할거라 생각)
- 각각의 user마다 email , phone number 둘 중 하나가 존재하면 다른 하나는 null을 허용하도록 할 수 있나요? (회원가입 시 email 혹은 phone number 중 하나만 있어도 가입 가능하게 하려함. 따라서 id로  쓰일 값 중 하나는 살아있게 하고자 함)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-14 08:56 UTC, kyeongraekim requested changes

2022-04-14 08:56 UTC, kyeongraekim commented on students/giseong/users/models.py
> +    user_email        = models.EmailField(max_length=128, null=False, unique=True)
장고 데이터 속성의 디폴트 값은 null=False임으로 혹시 꼭 명시해야하는 이유가 아니라면 생략해주셔도 무방합니다~

2022-04-14 08:56 UTC, kyeongraekim commented on students/giseong/users/models.py
> +    user_name         = models.CharField(max_length=20)
클래스 명에 User 인스턴스라는 것이 명시되어서 user_라는 표현이 중복으로 들어가게되면 코드상에서 verbose 하게 느껴질 수 있습니다.

2022-04-14 08:56 UTC, kyeongraekim commented on students/giseong/users/models.py
> +
데이터의 이력관리를 위해서 created_at 과 updated_at 칼럼을 추가해주세요~

2022-04-14 08:56 UTC, kyeongraekim commented on students/giseong/users/models.py
> +    user_phone_number = models.CharField(max_length=12, unique=True)
전세계 사용자의 전화번호가 들어올 수 있음으로 최대 길이수는 넉넉히 20~30 자 정도로 잡아주세요~
그리고 전화번호에 한해서 unique 제한이 꼭 필요해야할까요? 한 번 고민해보세요!~

2022-04-14 09:01 UTC, jiggyjiggy commented on students/giseong/users/models.py
> +    user_email        = models.EmailField(max_length=128, null=False, unique=True)
DB관점에서 users 테이블의 email , phone number 둘 중 하나가 존재하면 다른 하나는 null=True 하도록 할 수 있나요?

2022-04-14 09:03 UTC, jiggyjiggy commented on students/giseong/users/models.py
> +    user_name         = models.CharField(max_length=20)
네 조언해주신대로 수정해보겠습니다
제가 보기에도 verbose 해보이네요

2022-04-14 09:16 UTC, jiggyjiggy commented on students/giseong/users/models.py
> +
무엇을 위한 속성인지 모르겠습니다

어떤 류의 데이터 이력관리 인가요?
created_at 은 유저의 계정이 생성된 날짜
updated_at 은 최신 게시물 날짜 
를 의미하는건가요?

2022-04-14 09:50 UTC, kyeongraekim commented on students/giseong/users/models.py
> +
네 맞습니다. 유저 데이터의 생성 시기와 업데이트 시기에 대한 이력을 사측에서 왜 관리해야하는지 고민해보세요~

2022-04-14 10:33 UTC, jiggyjiggy commented on students/giseong/users/models.py
> +    user_phone_number = models.CharField(max_length=12, unique=True)
세계마다 전화번호 길이가 다르다는걸 깜빡했었네요 

한 사람이 여러개의 계정을 갖을 수 있기에 전화번호의 중복을 허용해야 한다 생각이 듭니다

그렇다면 email도 중복을 허용해도 된다 생각이 드는데 말씀 없으신걸 보면 
email이 user id 로써 쓰이는 건가요?

2022-04-15 02:22 UTC, kyeongraekim commented on students/giseong/users/models.py
> +    user_phone_number = models.CharField(max_length=12, unique=True)
- 곰곰이 생각해보시면 대부분의 사이트는 한 웹서비스에서 동일한 이메일 가입은 지양하고 있습니다. 다만 전화번호는 서로 다른 사람들이 동일한 번호를 사용하게되는 경우가 실생활에 많이 있어집니다. 따라서 unique값을 걸지 않는 것 입니다.

- user 테이블 데이터속 각각의 id 값이 pk 값으로 사용되는 것이고 email은 email로서 사용됩니다. 한국식 영어로서의 아이디는 영어표현으로는 username이 올바르며 만일 user_name이라는 항목이 유저의 실명이 아닌 앞서 말한 username으로서의 기능을 한다면 두개를 혼용해서 사용할 수 있겠네요.

2022-04-15 02:24 UTC, kyeongraekim commented on students/giseong/users/models.py
> +    user_email        = models.EmailField(max_length=128, null=False, unique=True)
네 해당내용은 테이블이 아닌 로직 선에서 조건을 걸어서 데이터들이 들어갈 수 있게 할 수 있겠네요

2022-04-15 04:37 UTC, closed without merging