[박현지] Mission 2: 모델링
wecode-bootcamp-korea/32-westagram-backend-2-team pull request #8
Opened 2022-04-14 09:40 UTC by celeste-6

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
- Created model for users app 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

Created models.py :
- Created User class containing instances "name", "email", "password", "mobile_number"

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시)

- 찾아보니 핸드폰번호에 `PhoneNumberField` 를 써도 되는것 같던데, CharField로 쓰는것 중에 더 선호되는 것이 있을까요?
- 보통 migration을 진행하고 push request를 하는게 맞는지 작업순서가 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-04-14 09:52 UTC, kyeongraekim requested changes

2022-04-14 09:52 UTC, kyeongraekim commented on students/hyunji/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.
```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)

2022-04-14 09:52 UTC, kyeongraekim commented on students/hyunji/users/models.py
> +    mobile_number = models.CharField(max_length=25, unique=True)
전화번호에 unique 속성 설정이 꼭 필수여야할까요? 한 번 고민해주세요!

2022-04-14 10:17 UTC, celeste-6 commented on students/hyunji/users/models.py
> +    mobile_number = models.CharField(max_length=25, unique=True)
만약 전화번호로 로그인을 한다면 Unique가 필수가 되야될것 같다고 생각했는데, 로그인을 어떤방식으로 하는지 아래쪽에 적혀있어서 보니 이메일로 하는거여서 전화번호는 꼭 필요하지 않겠네요. 어떤 요소를 사용해서 로그인을 하는지를 중요하게 봐야겠네요.

2022-04-15 01:54 UTC, kyeongraekim approved these changes
LGTM!~

2022-04-15 01:54 UTC, merged